### ISSUE TITLE
Failed resolution of: Lkhangtran/preferenceshelper/PreferencesHelper;

### ISSUE THREAD

**Issue by genie137** [tntkhang/realm-encryption-helper#2]
Hello! 

Your libary is not working due to a missing dependency. 
Can you fix this?

Stacktrace is included below, i replaced my package identifier with APP.
Tested on Emulator Pixel 2 Oreo

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: APP, PID: 3169
                  java.lang.NoClassDefFoundError: Failed resolution of: Lkhangtran/preferenceshelper/PreferencesHelper;
                      at com.github.tntkhang.realmencryptionhelper.RealmEncryptionHelper.<init>(RealmEncryptionHelper.java:65)
                      at com.github.tntkhang.realmencryptionhelper.RealmEncryptionHelper.initHelper(RealmEncryptionHelper.java:50)
                      at APP.MainActivity.initRealm(MainActivity.java:52)
                      at APP.MainActivity.initComponents(MainActivity.java:43)
                      at APPMainActivity.onCreate(MainActivity.java:22)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "khangtran.preferenceshelper.PreferencesHelper" on path: DexPathList`

**Comment by tntkhang** [comment]
Which android version were you testing?

**Comment by tntkhang** [comment]
Thank for reporting this bug, I checked and found the solution. Please update the version of library to 1.0.1 for fixing the issue:

`implementation 'com.github.tntkhang:realm-encryption-helper:1.0.1'`

Thanks.
